import { useEffect, useState } from 'react';
import ThumbnailsCard from '../../components/ThumbnailsCard';
import { Input, Spacer, Switch } from '@nextui-org/react';
import Head from 'next/head';
import HomepageCard from '@/components/HompageCard';
import RelatedCard from '@/components/RelatedCard';
import numbro from 'numbro';


export default function ThumbnailsPage() {
  const [inputValue, setInputValue] = useState('');
  const [imageList, setImageList] = useState([]);
  const [isViewedEnabled, setIsViewedEnabled] = useState(false);
  const [progress, setProgress] = useState(0);
  const [views, setViews] = useState(0);

  const handleTitleChange = (e) => {
    setInputValue(e.target.value);
  };

  const handleViewedToggle = () => {
    setIsViewedEnabled(!isViewedEnabled);

    if (!isViewedEnabled) {
      const randomProgress = Math.floor(Math.random() * 100);
      setProgress(randomProgress);
    }
  };

  useEffect(() => {
    if (isViewedEnabled) {
      setViews(Math.floor(Math.random() * 10000));
    } else {
      setViews(0);
    }
  }, [isViewedEnabled]);

  return (
    <>
      <Head>
        <title>YT Playlist Creator & Sharer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-4 mb-[50px] flex flex-col">
        <h1 className="text-center px-3 md:px-0 text-3xl">Thumbnails Page</h1>
        <section>
          <div className="flex flex-col md:flex-row justify-center items-center mt-8 gap-4">
            <Input
              type="text"
              onChange={handleTitleChange}
              className="w-full md:w-3/5 text-2xl px-4 md:px-0 placeholder-slate-400"
              placeholder="Add title"
              aria-labelledby="Title"
              value={inputValue}
            />
            <Switch checked={isViewedEnabled} onChange={handleViewedToggle} color="primary">
              Viewed
            </Switch>
          </div>
        </section>
        <section className="mt-8 md:px-10 px-4 w-full">
          <div className="">
            <h1 className='my-8 font-bold'>HOMEPAGE</h1>
            <div className="flex md:flex-wrap md:flex-row flex-col justify-start md:px-3 gap-2">
              { Array.apply(null, Array(2)).map((_, index) => (
                <>
                <HomepageCard
                  key={index}
                  index={index}
                  title={inputValue}
                  isViewedEnabled={isViewedEnabled}
                  imageList={imageList}
                  setImageList={setImageList}
                  progress={progress}
                  views={numbro(views * (index + 1)).format({
                    spaceSeparated: false,
                    average: true,
                  })}
                />
                  <Spacer x={3} />
                </>
              ))
              }
            </div>
            <Spacer y={10} />
            <h1 className='my-3 font-bold'>RELATED</h1>
            <div className="flex md:flex-wrap md:flex-row flex-col justify-start md:px-3 gap-2">
              { Array.apply(null, Array(2)).map((_, index) => (
                <>
                <RelatedCard
                  key={index}
                  index={index}
                  title={inputValue}
                  isViewedEnabled={isViewedEnabled}
                  imageList={imageList}
                  setImageList={setImageList}
                  progress={progress}
                  views={numbro(views * (index + 1)).format({
                    spaceSeparated: false,
                    average: true,
                  })}
                />
                <Spacer x={3} />
                </>
              ))
              }
          </div>
          </div>
        </section>
      </main>
    </>
  );
}
