import { useState } from 'react';
import ThumbnailsCard from '../../components/ThumbnailsCard';
import { Input, Spacer, Switch } from '@nextui-org/react';
import Head from 'next/head';
import HomepageCard from '@/components/HompageCard';
import RelatedCard from '@/components/RelatedCard';

export default function ThumbnailsPage() {
  const [inputValue, setInputValue] = useState('');
  const [imageList, setImageList] = useState([]);
  const [isViewedEnabled, setIsViewedEnabled] = useState(false);
  const [progress, setProgress] = useState(0);
  const [views, setViews] = useState(0);

  const handleTitleChange = (e) => {
    setInputValue(e.target.value);
  };

  // const handleFileSelect = (e) => {
  //   let files = [...e.target.files];
  //   if (fileList.length >= 2) {
  //     return;
  //   } else if (files && files.length > 0) {
  //     const fileType = files[0]['type'];
  //     const validImageTypes = ['image/jpeg', 'image/png', 'image/jpg'];
  //     if (validImageTypes.includes(fileType)) {
  //       setFileList([...fileList, files[0]]);
  //     } else {
  //       return;
  //     }
  //   }
  // };

  const handleViewedToggle = () => {
    setIsViewedEnabled(!isViewedEnabled);

    if (!isViewedEnabled) {
      const randomProgress = Math.floor(Math.random() * 100);
      setProgress(randomProgress);
    }
  };

  return (
    <>
      <Head>
        <title>YT Playlist Creator & Sharer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-4 mb-[50px] flex flex-col">
        <h1 className="text-center px-3 md:px-0 text-3xl">Thumbnails Page</h1>
        <section>
          <div className="flex flex-col md:flex-row justify-center items-center mt-8 gap-4">
            <Input
              type="text"
              onChange={handleTitleChange}
              className="w-full md:w-3/5 text-2xl px-4 md:px-0 placeholder-slate-400"
              placeholder="Add title"
              aria-labelledby="none"
              value={inputValue}
            />
            <Switch checked={isViewedEnabled} onChange={handleViewedToggle} color="primary">
              Viewed
            </Switch>
          </div>
        </section>
        <section className="mt-8 px-8">
          <h2 className="text-center text-2xl">Compare Thumbnails</h2>
          <div className="p-4 my-4 flex flex-col lg:flex-row lg:flex-wrap gap-6 justify-center">
          <>
              <h1 className='text-center my-8 font-bold'>HOME PAGE</h1>
              <div className="flex md:flex-wrap md:flex-row flex-col justify-center px-10 md:px-5 gap-4">
                { imageList.length > 0 && imageList.map((imageSrc, index) => (
                  <>
                  <HomepageCard
                    key={index}
                    title={inputValue}
                    isViewedEnabled={isViewedEnabled}
                    imageSrc={imageSrc}
                  />
                  <Spacer x={3} />
                  </>
                ))
                }
              </div>
              <Spacer y={10} />
              <h1 className='text-center my-8 font-bold'>RELATED</h1>
              <div className="flex md:flex-wrap md:flex-row flex-col justify-center px-10 md:px-5 gap-4">
              { imageList.length > 0 && imageList.map((imageSrc, index) => (
                <>
                <RelatedCard
                  key={index}
                  title={inputValue}
                  isViewedEnabled={isViewedEnabled}
                  imageSrc={imageSrc}
                />
                <Spacer x={3} />
                </>
              ))
              }
            </div>
            </>
              { Array.apply(null, Array(2)).map((_, index) => (
                  <ThumbnailsCard
                    key={index}
                    index={index}
                    title={inputValue}
                    isViewedEnabled={isViewedEnabled}
                    imageList={imageList}
                    setImageList={setImageList}
                    progress={progress}
                    setProgress={setProgress}
                    views={views}
                    setViews={setViews}
                  />
                ))}
          </div>
        </section>
      </main>
    </>
  );
}
