import Head from 'next/head';
import { useState } from 'react';


export default function ThumbnailsPage() {

    const [videoTitle, setVideoTitle] = useState('');

    const handleTitleChange = (event) => {
        setVideoTitle(event.target.value);
      };
  return (
    <>
      <Head>
        <title>YT Playlist Creator & Sharer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>Thumbnails Page</h1>
      <section>
        <h2>Video Details</h2>
        <div>
          <label htmlFor="video-title">Title:</label>
          <input
            id="video-title"
            type="text"
            value={videoTitle}
            onChange={handleTitleChange}
          />
        </div>
      </section>
      <section>
        <h2>Compare Thumbnails</h2>
        {/* Add your compare thumbnails components or content here */}
      </section>
    </>
  );
}
